version: '3'
services:
    e2e-db:
        image: mongo:latest
        restart: unless-stopped
        container_name: compitu-e2e-db
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: app
        volumes:
            - compitu-e2e-db-vol:/data/db
            - compitu-e2e-db-vol:/data/configdb
            - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro
        networks:
            - compitu-e2e-network
volumes:
    compitu-e2e-db-vol:
networks:
    compitu-e2e-network:
