version: '3'
services:
    db:
        image: mongo:latest
        restart: unless-stopped
        container_name: compitu-db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: app
        volumes:
            - compitu-db-vol:/data/db
            - compitu-db-vol:/data/configdb
            - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro
        networks:
            - compitu-network
volumes:
    compitu-db-vol:
networks:
    compitu-network:
